[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[rpc_endpoints]
localhost = "http://localhost:8545"
alfajores = "https://alfajores-forno.celo-testnet.org"

[etherscan]
alfajores = { key = "${ETHERSCAN_API_KEY}" }
